### ISSUE TITLE
Ctrl-C copy

### ISSUE THREAD

**Issue by lmrisdal** [skttl/ptrun-guid#1]
Super useful plugin! But would it be possible to add the ctrl-c copying of the selected guid?

**Comment by mediatech15** [comment]
@lmrisdal Are you wanting direct control for the copy process? The plugin auto copies it and places in the clipboard.

**Comment by lmrisdal** [comment]
@mediatech15 I honestly can't remember really, but I think it just was more intuitive for me to press CTRL+C than to press Enter to select a GUID.

**Comment by skttl** [comment]
I'm not even sure PowerToys allows you to do that.

**Comment by lmrisdal** [comment]
I wouldn't know, but totally fine if it isn't possible.
