### ISSUE TITLE
Not working anymore on PowerToys version 0.75.1

### ISSUE THREAD

**Issue by L-Wehmschulte** [skttl/ptrun-guid#2]
I just updated PowerToys to version 0.75.1. However this broke some Pllugins which I am using. Also sadly this one. Could you please look into supporting the new PowerToys version?

**Comment by pautx24** [comment]
Indeed, I have the same issue. This is one of the most useful plugins I've got and it's just pitty that the update broke it :(

**Comment by skttl** [comment]
Didn't even know anyone was using it :)

I'll look into supporting the new version, but can't promise when.

**Comment by mediatech15** [comment]
I was looking to put in a PR to fix this and the other issue to help speed up things. if thats fine @skttl 
@pautx24 @iTzScorpions  Do you know if it worked in 0.75.0?

**Comment by skttl** [comment]
You are very welcome @mediatech15

**Comment by dkaszews** [comment]
This is caused by additional security in 0.75.1, looking at another plugin it seems to be a one-line fix https://github.com/bostrot/PowerToysRunPluginWinget/pull/19

**Comment by L4hibYoussef** [comment]
You can use the built in guid feature in powertoys instead. Check the link: https://learn.microsoft.com/en-us/windows/powertoys/run#uuids

**Comment by pautx24** [comment]
Awesome! Thanks a lot!
________________________________

**Comment by skttl** [comment]
Thanks for pointing this out - I can deprecate this then :)
